name: TestMsBuild.Sdk
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
      
    - uses: nuget/setup-nuget@v1
      name: Nuget Restore
      with:
       nuget-version: '5.x'
    - run: nuget restore msSdk.sln
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Build and Publish Web App
      run: msbuild msSdk.sln /t:Publish /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingeFile=true /p:PackageLocation="./artifacts"
 
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: msSdkCiCd
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        
